hacker_news_ASW/config/routes.rb
Rails.application.routes.draw do

  resources :liked_comments
  resources :liked_posts
  resources :comentaris
   get '/submit/newest', to: 'submits#newest', as: 'newest_submit'
   get '/submit/index', to: 'submits#index', as: 'index_submit'
   post '/submits/comment', to: 'submits#comment', as: 'submits_comment'
   get '/comentaris/index', to: 'comentaris#index', as: 'index_comentaris'
   get '/submit/ask', to: 'submits#ask', as: 'ask_submit'

  
  resources :comentaris do
    put 'upvote_comment_update', on: :member
    put 'vote_comment', on: :member
    put 'unvote_comment', on: :member
  end

  resources :users

  resources :liked_submits
   get '/submit/newest', to: 'submits#newest', as: 'newest_submit2'
   get '/submit/index', to: 'submits#index', as: 'index_submit2'
   get '/users/:id/submits', to: 'users#submits'
   get '/users/:id/comments', to: 'users#comments'
   get '/users/:id/comments', to: 'users#comments.json'
   get '/users/:id/upvoted_submissions', to: 'users#upvoted_submissions'
   get '/users/:id/upvoted_comments', to: 'users#upvoted_comments'
   
  resources :submits do
    put 'upvote_update', on: :member
    put 'vote', on: :member
    put 'unvote', on: :member
  end
  
  resources :usuaris
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get '/auth/google_oauth2/callback', to: 'sessions#omniauth'
  get '/logout', to: 'sessions#destroy', as: 'logout'
  get '/submits/new/auth/google_oauth2/callback', to: 'sessions#omniauth'
  
 
  root 'submits#index'
end

hacker_news_ASW/app/models/liked_post.rb
class LikedPost < ApplicationRecord
  belongs_to :submit
  belongs_to :user
end

hacker_news_ASW/app/controllers/liked_posts_controller.rb
class LikedPostsController < ApplicationController
  before_action :set_liked_post, only: [:show, :edit, :update, :destroy]

  # GET /liked_posts
  # GET /liked_posts.json
  def index
    @liked_posts = LikedPost.all
  end

  # GET /liked_posts/1
  # GET /liked_posts/1.json
  def show
  end

  # GET /liked_posts/new
  def new
    @liked_post = LikedPost.new
  end

  # GET /liked_posts/1/edit
  def edit
  end

  # POST /liked_posts
  # POST /liked_posts.json
  def create
    @liked_post = LikedPost.new(liked_post_params)

    respond_to do |format|
      if @liked_post.save
        format.html { redirect_to @liked_post, notice: 'Liked post was successfully created.' }
        format.json { render :show, status: :created, location: @liked_post }
      else
        format.html { render :new }
        format.json { render json: @liked_post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /liked_posts/1
  # PATCH/PUT /liked_posts/1.json
  def update
    respond_to do |format|
      if @liked_post.update(liked_post_params)
        format.html { redirect_to @liked_post, notice: 'Liked post was successfully updated.' }
        format.json { render :show, status: :ok, location: @liked_post }
      else
        format.html { render :edit }
        format.json { render json: @liked_post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /liked_posts/1
  # DELETE /liked_posts/1.json
  def destroy
    @liked_post.destroy
    respond_to do |format|
      format.html { redirect_to liked_posts_url, notice: 'Liked post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_liked_post
      @liked_post = LikedPost.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def liked_post_params
      params.require(:liked_post).permit(:submit_id, :user_id)
    end
end

hacker_news_ASW/app/helpers/liked_posts_helper.rb
module LikedPostsHelper
end

hacker_news_ASW/app/views/liked_posts/_form.html.erb
<%= form_with(model: liked_post) do |form| %>
  <% if liked_post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(liked_post.errors.count, "error") %> prohibited this liked_post from being saved:</h2>

      <ul>
        <% liked_post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :submit_id %>
    <%= form.text_field :submit_id %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

hacker_news_ASW/app/views/liked_posts/edit.html.erb
<h1>Editing Liked Post</h1>

<%= render 'form', liked_post: @liked_post %>

<%= link_to 'Show', @liked_post %> |
<%= link_to 'Back', liked_posts_path %>

hacker_news_ASW/app/views/liked_posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Liked Posts</h1>

<table>
  <thead>
    <tr>
      <th>Submit</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @liked_posts.each do |liked_post| %>
      <tr>
        <td><%= liked_post.submit_id %></td>
        <td><%= liked_post.user_id %></td>
        <td><%= link_to 'Show', liked_post %></td>
        <td><%= link_to 'Edit', edit_liked_post_path(liked_post) %></td>
        <td><%= link_to 'Destroy', liked_post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Liked Post', new_liked_post_path %>

hacker_news_ASW/app/views/liked_posts/new.html.erb
<h1>New Liked Post</h1>

<%= render 'form', liked_post: @liked_post %>

<%= link_to 'Back', liked_posts_path %>

hacker_news_ASW/app/views/liked_posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Submit:</strong>
  <%= @liked_post.submit_id %>
</p>

<p>
  <strong>User:</strong>
  <%= @liked_post.user_id %>
</p>

<%= link_to 'Edit', edit_liked_post_path(@liked_post) %> |
<%= link_to 'Back', liked_posts_path %>