hacker_news_ASW/config/routes.rb
Rails.application.routes.draw do

  resources :liked_comments
  resources :liked_posts
  resources :comentaris
   get '/submit/newest', to: 'submits#newest', as: 'newest_submit'
   get '/submit/index', to: 'submits#index', as: 'index_submit'
   post '/submits/comment', to: 'submits#comment', as: 'submits_comment'
   get '/comentaris/index', to: 'comentaris#index', as: 'index_comentaris'
   get '/submit/ask', to: 'submits#ask', as: 'ask_submit'

  
  resources :comentaris do
    put 'upvote_comment_update', on: :member
    put 'vote_comment', on: :member
    put 'unvote_comment', on: :member
  end

  resources :users

  resources :liked_submits
   get '/submit/newest', to: 'submits#newest', as: 'newest_submit2'
   get '/submit/index', to: 'submits#index', as: 'index_submit2'
   get '/users/:id/submits', to: 'users#submits'
   get '/users/:id/comments', to: 'users#comments'
   get '/users/:id/comments', to: 'users#comments.json'
   get '/users/:id/upvoted_submissions', to: 'users#upvoted_submissions'
   get '/users/:id/upvoted_comments', to: 'users#upvoted_comments'
   
  resources :submits do
    put 'upvote_update', on: :member
    put 'vote', on: :member
    put 'unvote', on: :member
  end
  
  resources :usuaris
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get '/auth/google_oauth2/callback', to: 'sessions#omniauth'
  get '/logout', to: 'sessions#destroy', as: 'logout'
  get '/submits/new/auth/google_oauth2/callback', to: 'sessions#omniauth'
  
 
  root 'submits#index'
end

hacker_news_ASW/app/models/comentari.rb
class Comentari < ApplicationRecord
end

hacker_news_ASW/app/controllers/comentaris_controller.rb
class ComentarisController < ApplicationController
  before_action :set_comentari, only: [:show, :edit, :update, :destroy, :upvote_comment_update, :vote_comment, :unvote_comment]
  
  ############
  #La API KEY s'ha de mirar en cada endpoint que faci falta, dintre de format.json, perquè si accedeixes des del navegador peta perquè el navegador no posa el header
  #api_key = request.headers[:HTTP_X_API_KEY]
  ############
  
  # GET /comentaris
  # GET /comentaris.json
  def index
      respond_to do |format|
        format.html {
          if(!session[:user_email].nil?)
            @user = User.find(session[:user_id])
            @comment = Comentari.all.where(:user_id => @user.id)
            @current_user_likes_comment = []
            if session[:user_email]
              @current_user_likes_comment=LikedComment.where(user_id: session[:user_id])
            end
            render :index
          end
        }
        format.json  {
          @user = User.all.where(:ltoken => request.headers["X-API-Key"]).first()
          if @user.nil?
            render json: {"status": 401,
            "error": "Unauthorized",
            "message": "You provided no api key or incorrect api key(X-API-KEY Header)"}, status: :unauthorized
            return
          end
          @comment = Comentari.all.where(:user_id => @user.id)
          comments = []
          @comment.each do |c|
            @upvotes = LikedComment.all.where(:comentari_id => c.id)
            upvote_ids = []
            @upvotes.each do |u|
              upvote_ids.push(u.user_id)
            end
              
            comments.push({
              "id": c.id,
              "text": c.text,
              "respondsToId": c.respondsToId,
              "postID": c.postID,
              "created_at": c.created_at,
              "likes": c.likes,
              "user_id": c.user_id,
              "upvote_ids": upvote_ids
            })
          end
          render json: comments.to_json
        }
      end
  end


  # GET /comentaris/1
  # GET /comentaris/1.json
  def show
    @comentari = Comentari.find(params[:id])
    @submit = Submit.find(@comentari.postID)
    @current_user_likes_comment = []
    if session[:user_email]
      @current_user_likes_comment=LikedComment.where(user_id: session[:user_id])
    end
  end

  # GET /comentaris/new
  def new
    @comentari = Comentari.new
  end

  # GET /comentaris/1/edit
  def edit
  end

  # POST /comentaris
  # POST /comentaris.json
  def create
    if(comentari_params[:text].blank?)
    else
      respond_to do |format|
        format.html { 
          @comentari = Comentari.new(comentari_params)
          @comentari.likes|=1
          if @comentari.save
            redirect_to @comentari, notice: 'Comentari was successfully created.'
          else
            render :new
          end
        }
        format.json{
          if request.headers["X-API-Key"].blank?
            render json: {
                "status": 401,
                "message": "You provided no api key (X-API-KEY Header)"
              }, status: 401
          else 
            @user = User.all.where(:ltoken => request.headers["X-API-Key"]).first()
            if @user.nil?
              render json: {
                "status": 403,
                "message": "Your api key (X-API-KEY Header) is not valid"
              }, status: 403
              return
            end
            @comentari = Comentari.new(comentari_params)
            if @comentari.respondsToId > 0
              @comentari2 = Comentari.find(@comentari.respondsToId)
              if(@comentari2.postID != @comentari.postID)
                render json: {
                "status": 404,
                "message": "The respondsToId comment is not on the PostID post"
              }, status: 404
              return
              end
            end  
            @comentari.likes|=1
            @comentari.user_id=@user.id
            if @comentari.save
              render json: {
                "status": 200,
                "commentId": @comentari.id,
                "message": "Comment posted successfully"
              }, status: :ok
            else
              render json: {
                "status": 403,
                "message": "Couldn't save comment"
              }, status: 403
            end
          end
        }
      end
    end
  end

  # PATCH/PUT /comentaris/1
  # PATCH/PUT /comentaris/1.json
  def update
    respond_to do |format|
      if @comentari.update(comentari_params)
        format.html { redirect_to @comentari, notice: 'Comentari was successfully updated.' }
        format.json { render :show, status: :ok, location: @comentari }
      else
        format.html { render :edit }
        format.json { render json: @comentari.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comentaris/1
  # DELETE /comentaris/1.json
  def destroy
    @comentari.destroy
    respond_to do |format|
      format.html { redirect_to comentaris_url, notice: 'Comentari was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comentari
      @comentari = Comentari.where(id: params[:id]).first
      if !@comentari
        not_found2
      end
    end

    # Only allow a list of trusted parameters through.
    def comentari_params
      params.require(:comentari).permit(:text, :user_id, :postID, :respondsToId)
    end
  end

hacker_news_ASW/app/helpers/comentaris_helper.rb
module ComentarisHelper
end

hacker_news_ASW/app/views/comentaris/_form.html.erb
<%= form_with(model: comentari) do |form| %>
  <% if comentari.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(comentari.errors.count, "error") %> prohibited this comentari from being saved:</h2>

      <ul>
        <% comentari.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :text %>
    <%= form.text_field :text %>
  </div>

  <div class="field">
    <%= form.label :user %>
    <%= form.text_field :user %>
  </div>

  <div class="field">
    <%= form.label :postID %>
    <%= form.text_field :postID %>
  </div>

  <div class="field">
    <%= form.label :respondsToId %>
    <%= form.text_field :respondsToId %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

hacker_news_ASW/app/views/comentaris/edit.html.erb
<h1>Editing Comentari</h1>

<%= render 'form', comentari: @comentari %>

<%= link_to 'Show', @comentari %> |
<%= link_to 'Back', comentaris_path %>

hacker_news_ASW/app/views/comentaris/index.html.erb
<center>
<table id="hnmain" width="85%" cellspacing="0" cellpadding="0" border="0" bgcolor="#f6f6ef">
  <tbody>
    <tr>
      <td bgcolor = "#ff6600"  class="tda">
         <table style="padding:2px" width="100%" cellspacing="0" cellpadding="0" border="0">
          <tbody >
            <tr>
               <td style="width:18px; padding-right:4px"  class="tda">
                 <a href="https://www.youtube.com/watch?v=PwbqAJKNdXo">
                   <img src="/y18.gif" style="border:1px white solid;"
                   width = "18" height = "18" >
                 </a>
                </td>
                <td style = "line-height:12pt; height:10px;"  class="tda">
                  <span class="pagetop">
                    <div style="display: inline-block;">
                      <b class="hnname"><a href=<%=index_submit_path%>>Hacker News</a></b>
                     <a  style="color: black"href=<%=newest_submit_path%>>new</a> | 
                     </div>
                     <% if session[:user_name]%>
                      <a href="/comentaris">threads</a>
                    <% else %>
                      <div style="display: inline-block">
                        <%= button_to "threads", '/auth/google_oauth2', form_class: "submit-button" %>
                      </div>
                    <% end%>
                    <div style="display: inline-block;">
                      | <a style="color: black">past</a> | <a style="color: black">comments</a> | <a style="color: black" href=<%=ask_submit_path%>>ask</a> | <a style="color: black">show</a> | <a style="color: black">jobs</a> |
                     </div>
                    <% if session[:user_name]%>
                      <a href=<%= new_submit_path %>>submit</a>
                    <% else %>
                      <div style="display: inline-block">
                        <%= button_to "submit", '/auth/google_oauth2', form_class: "submit-button" %>
                      </div>
                    <% end%>
                    <div style="display: inline-block;">
                      <div style="display: inline"> | </div>
                      <p style="display: inline; color: white; margin: 0"><%= @user.name + '\'s comments' %></p>
                    </div>
                  </span>
                </td>
                <td style="text-align:right;padding-right:4px;"  class="tda">
                  <span class="pagetop">
                    <% if session[:user_name]%>
                  <a href=<%= "/users/" + session[:user_id].to_s %>> <%= session[:user_name] + " ("  + session[:user_karma].to_s + ")"%> </a>
                  <p style="display: inline"> | </p>
                  <a style="display: inline" href=<%= logout_path %>>logout</a>
                    <% else %>
                      <%= button_to "login", '/auth/google_oauth2', form_class: "login-button" %>
                    <% end%>
                  </span>
                </td>
            </tr>
            </tbody>
        </table>
      </td>
    </tr>
    <tr>
      <td>
          <tbody>
            <%
            @comment = @comment.to_a
            arrOffsets = Array.new(@comment.size, 0)
            %>
             <% for i in 0..@comment.length-1%>
             <tr class="athing comtr" id="<%=@comment[i].id%>">
               <td>
                <table border="0">  
                  <tbody>
                    <tr>
                      <td class="default">
                        <div style="margin-top:2px; margin-bottom:-10px; display:flex">
                           <% if session[:user_email]%>
                      <% if  @comment[i].user_id == session[:user_id] %>
                        <center><div style="color: #ff6600">*</div></center>
                      <% elsif !@current_user_likes_comment.exists?(comentari_id: @comment[i].id) %>
                          <center><a rel="nofollow" data-method="put" href=<%= "/comentaris/" + @comment[i].id.to_s + "/upvote_comment_update"%>><div class="votearrow" title="upvote"></div></a></center>
                      <% else %>
                          <a rel="nofollow" data-method="put" href=<%= "/comentaris/" + @comment[i].id.to_s + "/upvote_comment_update"%>><div class="votearrow" style="transform: rotate(180deg);" title="upvote"></div></a>
                      <% end %>
                      <% end %>
                          <span class="comhead" style="margin-left:5px">
                            <a class="hnuser"><%=User.find(@comment[i].user_id).name%></a> 
                            <span class="age">
                              <a><% time = (Time.now() - @comment[i].created_at) %>

                              <% if time < 3600 %>
                                <a ><%= (time/60).round %> minutes ago</a>   
                              <% end %>

                              <% if time >= 3600 && time < 3600*24 %>
                                  <a ><%= (time/3600).round %> hours ago</a>  
                              <% end %>

                              <% if time >= 3600*24 %>
                                  <a><%= (time/(3600*24)).round %> days ago</a>  
                              <% end %> </a>
                            </span> 
                            <span>
                             on: <a href= <%= "/submits/" + @comment[i].postID.to_s %>> <%= @comment[i].respondsToId != 0 ? Comentari.find(@comment[i].respondsToId).text : Submit.find(@comment[i].postID).title %> </a> 
                            </span>
                            <span class="par"></span> 
                         
                            <span class="storyon"></span>
                          </span>
                        </div>
                        <div class="comment">
                          <span class="commtext c00"><%= simple_format(@comment[i].text)%>
                            <div class="reply">        
                              
                                <font size="1">
                                  <u><a href="/comentaris/<%=@comment[i].id%>">reply</a></u>
                                </font>
                              </br>
                            </div>
                          </span>
                        </div>
                      </td>
                    </tr>
                  </tbody>
                </table>
              </tr>
             <% end %>
          </tbody>
        </table>
        
      </td>
    </tr>
  </tbody>
</table>
</center>

hacker_news_ASW/app/views/comentaris/new.html.erb
<h1>New Comentari</h1>

<%= render 'form', comentari: @comentari %>

<%= link_to 'Back', comentaris_path %>

hacker_news_ASW/app/views/comentaris/show.html.erb
<center>
<table id="hnmain" width="85%" cellspacing="0" cellpadding="0" border="0" bgcolor="#f6f6ef">
  <tbody>
    <tr>
      <td bgcolor = "#ff6600"  class="tda">
        <table style="padding:2px" width="100%" cellspacing="0" cellpadding="0" border="0">
          <tbody >
            <tr>
             <td style="width:18px; padding-right:4px"  class="tda">
               <a href="https://www.youtube.com/watch?v=PwbqAJKNdXo">
                 <img src="/y18.gif" style="border:1px white solid;"
                 width = "18" height = "18" >
               </a>
              </td>
              <td style = "line-height:12pt; height:10px;"  class="tda">
                <span class="pagetop">
                  <b class="hnname">Add Comment</b>
                </span>
            </tr>
            </tbody>
        </table>
      </td>
    </tr>
    <tr id="pagespace" title="Add Comment" style="height:10px"></tr>
    <tr>
      <td>
        <table class="fatitem" border="0">
          <tbody>
            <tr class="athing" id="<%= @comentari.id %>">
              <td class = "ind" ></td>
              <td style="display: flex">
                <div style="margin-right: 5px">
                  <% if session[:user_email]%>
                      <% if  @comentari.user_id == session[:user_id] %>
                        <center><div style="color: #ff6600">*</div></center>
                      <% elsif !@current_user_likes_comment.exists?(comentari_id: @comentari.id) %>
                          <center><a rel="nofollow" data-method="put" href=<%= "/comentaris/" + @comentari.id.to_s + "/upvote_comment_update"%>><div class="votearrow" title="upvote"></div></a></center>
                      <% else %>
                          <a rel="nofollow" data-method="put" href=<%= "/comentaris/" + @comentari.id.to_s + "/upvote_comment_update"%>><div class="votearrow" style="transform: rotate(180deg);" title="upvote"></div></a>
                      <% end %>
                  <% end %></div></td>
              <td class="default">
                <div style="margin-top:2px; margin-bottom:-10px;">
                  <span class="comhead">
                    <a href=<%= "/users/" + session[:user_id].to_s %> class="hnuser">
                      <%=User.find(@comentari.user_id).name%>
                    </a> 
                    <span class="age">
                              <a><% time = (Time.now() - @comentari.created_at) %>

                              <% if time < 3600 %>
                                <a ><%= (time/60).round %> minutes ago</a>   
                              <% end %>

                              <% if time >= 3600 && time < 3600*24 %>
                                  <a ><%= (time/3600).round %> hours ago</a>  
                              <% end %>

                              <% if time >= 3600*24 %>
                                  <a><%= (time/(3600*24)).round %> days ago</a>  
                              <% end %> </a>
                    </span>  
                    <span id="unv_26682902"></span>
                    <span class="par">
                       | <a>parent</a>
                    </span> 
                    <a class="togg" n="11">
                      [–]
                    </a>          
                    <span class="storyon"> | on: 
                    <a>
                      <%=@submit.title[0..50]%>
                      <%if @submit.title.length>50%>
                        . . .
                      <%end%>
                    </a>
                    </span>
                  </span>
                </div>
                <br>
                <div class="comment">
                  <span class="commtext c5a" style="color:black"> <%=simple_format(@comentari.text)%>
                    <div class="reply"></div>
                  </span>
                </div>
              </td>
            </tr>
            <tr style="height:10px"></tr>
            <tr>
              <td colspan="2"></td>
              <td>
                <form method="post" action="/submits/comment">
                  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
                  <input type="hidden" name="comentari[user_id]" value=<%= session[:user_id] %>>
                  <input type="hidden" name="comentari[postID]" value="<%= @submit.id%>">
                  <input type="hidden" name="comentari[respondsToId]" value="<%=@comentari.id%>">
                  <input type="hidden" name="comentari[likes]" value="1">
                  <textarea name="comentari[text]" rows="6" cols="60"></textarea>
                  <br><br>
                  <span class="subtext">If you haven't already, would you mind reading about HN's
                    <a><u>approach to comments</u></a>
                      and 
                    <a>
                    <u>site guidelines</u></a>?
                  </span>
                  <br><br>
                  <input type="submit" value="reply">
                </form>
              </td>
            </tr>
          </tbody>
        </table>
      </td>
    </tr>
  </tbody>
</table>
</center>










<!--<p id="notice"><%= notice %></p>

<p>
  <strong>Text:</strong>
  <%= @comentari.text %>
</p>

<p>
  <strong>User:</strong>
  <%=User.find(@comentari.user_id).name%>
</p>

<p>
  <strong>Postid:</strong>
  <%= @comentari.postID %>
</p>

<p>
  <strong>Respondstoid:</strong>
  <%= @comentari.respondsToId %>
</p>

<%= link_to 'Edit', edit_comentari_path(@comentari) %> |
<%= link_to 'Back', comentaris_path %>-->