hacker_news_ASW/config/routes.rb
Rails.application.routes.draw do

  resources :liked_comments
  resources :liked_posts
  resources :comentaris
   get '/submit/newest', to: 'submits#newest', as: 'newest_submit'
   get '/submit/index', to: 'submits#index', as: 'index_submit'
   post '/submits/comment', to: 'submits#comment', as: 'submits_comment'
   get '/comentaris/index', to: 'comentaris#index', as: 'index_comentaris'
   get '/submit/ask', to: 'submits#ask', as: 'ask_submit'

  
  resources :comentaris do
    put 'upvote_comment_update', on: :member
    put 'vote_comment', on: :member
    put 'unvote_comment', on: :member
  end

  resources :users

  resources :liked_submits
   get '/submit/newest', to: 'submits#newest', as: 'newest_submit2'
   get '/submit/index', to: 'submits#index', as: 'index_submit2'
   get '/users/:id/submits', to: 'users#submits'
   get '/users/:id/comments', to: 'users#comments'
   get '/users/:id/comments', to: 'users#comments.json'
   get '/users/:id/upvoted_submissions', to: 'users#upvoted_submissions'
   get '/users/:id/upvoted_comments', to: 'users#upvoted_comments'
   
  resources :submits do
    put 'upvote_update', on: :member
    put 'vote', on: :member
    put 'unvote', on: :member
  end
  
  resources :usuaris
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get '/auth/google_oauth2/callback', to: 'sessions#omniauth'
  get '/logout', to: 'sessions#destroy', as: 'logout'
  get '/submits/new/auth/google_oauth2/callback', to: 'sessions#omniauth'
  
 
  root 'submits#index'
end

hacker_news_ASW/app/models/liked_comment.rb
class LikedComment < ApplicationRecord
  belongs_to :user
  belongs_to :comentari
end

hacker_news_ASW/app/controllers/liked_comments_controller.rb
class LikedCommentsController < ApplicationController
  before_action :set_liked_comment, only: [:show, :edit, :update, :destroy]

  # GET /liked_comments
  # GET /liked_comments.json
  def index
    @liked_comments = LikedComment.all
  end

  # GET /liked_comments/1
  # GET /liked_comments/1.json
  def show
  end

  # GET /liked_comments/new
  def new
    @liked_comment = LikedComment.new
  end

  # GET /liked_comments/1/edit
  def edit
  end

  # POST /liked_comments
  # POST /liked_comments.json
  def create
    @liked_comment = LikedComment.new(liked_comment_params)

    respond_to do |format|
      if @liked_comment.save
        format.html { redirect_to @liked_comment, notice: 'Liked comment was successfully created.' }
        format.json { render :show, status: :created, location: @liked_comment }
      else
        format.html { render :new }
        format.json { render json: @liked_comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /liked_comments/1
  # PATCH/PUT /liked_comments/1.json
  def update
    respond_to do |format|
      if @liked_comment.update(liked_comment_params)
        format.html { redirect_to @liked_comment, notice: 'Liked comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @liked_comment }
      else
        format.html { render :edit }
        format.json { render json: @liked_comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /liked_comments/1
  # DELETE /liked_comments/1.json
  def destroy
    @liked_comment.destroy
    respond_to do |format|
      format.html { redirect_to liked_comments_url, notice: 'Liked comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_liked_comment
      @liked_comment = LikedComment.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def liked_comment_params
      params.require(:liked_comment).permit(:user_id, :comentari_id)
    end
end

hacker_news_ASW/app/helpers/liked_comments_helper.rb
module LikedCommentsHelper
end

hacker_news_ASW/app/views/liked_comments/_form.html.erb
<%= form_with(model: liked_comment) do |form| %>
  <% if liked_comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(liked_comment.errors.count, "error") %> prohibited this liked_comment from being saved:</h2>

      <ul>
        <% liked_comment.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id %>
  </div>

  <div class="field">
    <%= form.label :comentari_id %>
    <%= form.text_field :comentari_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

hacker_news_ASW/app/views/liked_comments/edit.html.erb
<h1>Editing Liked Comment</h1>

<%= render 'form', liked_comment: @liked_comment %>

<%= link_to 'Show', @liked_comment %> |
<%= link_to 'Back', liked_comments_path %>

hacker_news_ASW/app/views/liked_comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Liked Comments</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Comentari</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @liked_comments.each do |liked_comment| %>
      <tr>
        <td><%= liked_comment.user_id %></td>
        <td><%= liked_comment.comentari_id %></td>
        <td><%= link_to 'Show', liked_comment %></td>
        <td><%= link_to 'Edit', edit_liked_comment_path(liked_comment) %></td>
        <td><%= link_to 'Destroy', liked_comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Liked Comment', new_liked_comment_path %>

hacker_news_ASW/app/views/liked_comments/new.html.erb
<h1>New Liked Comment</h1>

<%= render 'form', liked_comment: @liked_comment %>

<%= link_to 'Back', liked_comments_path %>

hacker_news_ASW/app/views/liked_comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @liked_comment.user_id %>
</p>

<p>
  <strong>Comentari:</strong>
  <%= @liked_comment.comentari_id %>
</p>

<%= link_to 'Edit', edit_liked_comment_path(@liked_comment) %> |
<%= link_to 'Back', liked_comments_path %>