hacker_news_ASW/config/routes.rb
Rails.application.routes.draw do

  resources :liked_comments
  resources :liked_posts
  resources :comentaris
   get '/submit/newest', to: 'submits#newest', as: 'newest_submit'
   get '/submit/index', to: 'submits#index', as: 'index_submit'
   post '/submits/comment', to: 'submits#comment', as: 'submits_comment'
   get '/comentaris/index', to: 'comentaris#index', as: 'index_comentaris'
   get '/submit/ask', to: 'submits#ask', as: 'ask_submit'

  
  resources :comentaris do
    put 'upvote_comment_update', on: :member
    put 'vote_comment', on: :member
    put 'unvote_comment', on: :member
  end

  resources :users

  resources :liked_submits
   get '/submit/newest', to: 'submits#newest', as: 'newest_submit2'
   get '/submit/index', to: 'submits#index', as: 'index_submit2'
   get '/users/:id/submits', to: 'users#submits'
   get '/users/:id/comments', to: 'users#comments'
   get '/users/:id/comments', to: 'users#comments.json'
   get '/users/:id/upvoted_submissions', to: 'users#upvoted_submissions'
   get '/users/:id/upvoted_comments', to: 'users#upvoted_comments'
   
  resources :submits do
    put 'upvote_update', on: :member
    put 'vote', on: :member
    put 'unvote', on: :member
  end
  
  resources :usuaris
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get '/auth/google_oauth2/callback', to: 'sessions#omniauth'
  get '/logout', to: 'sessions#destroy', as: 'logout'
  get '/submits/new/auth/google_oauth2/callback', to: 'sessions#omniauth'
  
 
  root 'submits#index'
end

hacker_news_ASW/app/models/submit.rb
class Submit < ApplicationRecord
end

hacker_news_ASW/app/controllers/submits_controller.rb
class SubmitsController < ApplicationController
  before_action :set_submit, only: [:show, :edit, :update, :destroy, :like, :upvote_update, :vote, :unvote]
  require 'uri'
  require "net/http"
  # GET /submits
  # GET /submits.json
  def index
    @submit = Submit.all.where(:text => "").order(like: :desc)
    @current_user_likes = []
    if session[:user_email]
      @current_user_likes=LikedPost.where(user_id: session[:user_id])
    end
    respond_to do |format|
        format.html {render :index}
        format.json {
          submits = []
          @submit.each do |s|
            @upvotes = LikedPost.all.where(:submit_id => s.id)
            @comment = Comentari.all.where(:postID => s.id)
            @user = User.find(s.user_id)
            upvote_ids = []
            @upvotes.each do |u|
              upvote_ids.push(u.user_id)
            end
            submits.push({
              "id": s.id,
              "title": s.title,
              "url": s.URL,
              "text": s.text,
              "created_at": s.created_at,
              "likes": s.like,
              "user_name": @user.name,
              "user_id": s.user_id,
              "upvote_ids": upvote_ids,
              "number_comments": @comment.count
              
            })
          end
          render json: submits.to_json , status: :ok
        }
    end
  end
  # GET /submits/1
  # GET /submits/1.json
  def show
    @submit = Submit.find(params[:id])
    @comment = Comentari.all.where(:postID => params[:id]).order(:respondsToId)
    @current_user_likes = []
    
    if session[:user_email]
      @current_user_likes=LikedPost.where(user_id: session[:user_id])
    end
    
    @current_user_likes_comment = []
    if session[:user_email]
      @current_user_likes_comment=LikedComment.where(user_id: session[:user_id])
    end
    
    respond_to do |format|
      format.html {render :show}
      
      format.json  { 
        submits = []
        @upvotes = LikedPost.all.where(:submit_id => @submit.id)
        upvote_ids = []
        @user = User.find(@submit.user_id)
        @upvotes.each do |u|
          upvote_ids.push(u.user_id)
        end
        submits.push({
          "id": @submit.id,
          "title": @submit.title,
          "url": @submit.URL,
          "text": @submit.text,
          "created_at": @submit.created_at,
          "likes": @submit.like,
          "user_id": @submit.user_id,
          "user_name": @user.name,
          "upvote_ids": upvote_ids
        })
        comments = []
        @comment.each do |c|
            @upvotes = LikedComment.all.where(:comentari_id => c.id)
            upvote_ids = []
            @upvotes.each do |u|
              upvote_ids.push(u.user_id)
            end
            respondsTo = ""
            if(c.respondsToId == 0)
              @respondsPost = Submit.find(c.postID)
              respondsTo = @respondsPost.title
            else
              @respondsComment = Comentari.find(c.respondsToId)
              respondsTo = @respondsComment.text
            end
            comments.push({
              "id": c.id,
              "text": c.text,
              "respondsToId": c.respondsToId,
              "postID": c.postID,
              "created_at": c.created_at,
              "likes": c.likes,
              "user_id": c.user_id,
              "upvote_ids": upvote_ids,
              "respondsTo": respondsTo
            })
        end
        render :json => {:submit => submits, :comment => comments }
      }
    end
  end

  # GET /submits/new
  def new
      @submit = Submit.new
  end

  # GET /submits/1/edit
  def edit
  end
  
  # GET /submit_urls/newest
  def newest
   @submit = Submit.all.order(created_at: :desc)
    @current_user_likes = []
    if session[:user_email]
      @current_user_likes=LikedPost.where(user_id: session[:user_id])
    end
    respond_to do |format|
        format.html {render :newest}
        format.json {
          submits = []
          @submit.each do |s|
            @upvotes = LikedPost.all.where(:submit_id => s.id)
            @comment = Comentari.all.where(:postID => s.id)
            @user = User.find(s.user_id)
            upvote_ids = []
            @upvotes.each do |u|
              upvote_ids.push(u.user_id)
            end
            submits.push({
              "id": s.id,
              "title": s.title,
              "url": s.URL,
              "text": s.text,
              "created_at": s.created_at,
              "likes": s.like,
              "user_name": @user.name,
              "user_id": s.user_id,
              "upvote_ids": upvote_ids,
              "number_comments": @comment.count
              
            })
          end
          render json: submits.to_json , status: :ok
        }
    end
  end
  
  def ask #edit
    @submit = Submit.all.where(:URL => "").order(created_at: :desc)
    @current_user_likes = []
    if session[:user_email]
      @current_user_likes=LikedPost.where(user_id: session[:user_id])
    end
    respond_to do |format|
        format.html {render :ask}
        format.json  {
          submits = []
          @submit.each do |s|
            @comment = Comentari.all.where(:postID => s.id)
            @user = User.find(s.user_id)
            @upvotes = LikedPost.all.where(:submit_id => s.id)
            upvote_ids = []
            @upvotes.each do |u|
              upvote_ids.push(u.user_id)
            end
            submits.push({
              "id": s.id,
              "title": s.title,
              "url": s.URL,
              "text": s.text,
              "created_at": s.created_at,
              "likes": s.like,
              "user_id": s.user_id,
              "user_name": @user.name,
              "upvote_ids": upvote_ids,
              "number_comments": @comment.count
            })
          end
          render json: submits.to_json , status: :ok}
    end
  end 

  # POST /submits
  # POST /submits.json
  def create
    
    #if @user.ltoken == request.headers["X-API-Key"]
    
    @submit = Submit.new(submit_params)

    respond_to do |format|
      format.json { 
        @user = User.all.where(:ltoken => request.headers["X-API-Key"]).first()
        if @user.nil?
          render json: {"status": 401,
          "error": "Unauthorized",
          "message": "You provided no api key or incorrect api key(X-API-KEY Header)"}, status: :unauthorized
          return
        else 
          @submit.user_id=@user.id
          session[:user_id]=@user.id
          session[:user_karma]=@user.karma
        end
      }
       format.html {} 
    end
    
    if(@submit.URL.empty? || @submit.URL =~ /\A#{URI::regexp}\z/) 
      #donothing
    else
      respond_to do |format|
        format.html { redirect_to "/submits/new"
          return
        }
        format.json {  
          render json: {"status": 422,
          "error": "Unprocessable entity",
          "message": "You provided neither title nor url or text or wrong URL"}, status: :unprocessable_entity
          return }
      end
    end
  
    if (!@submit.URL.empty? && !url_exist?(@submit.URL))
        respond_to do |format|
        format.html { render :new }
        format.json { render json: {
          "status": 422,
          "error": "Unprocessable entity",
          "message": "You provided neither title nor url or text or wrong URL"}, status: :unprocessable_entity }
        end
      
    else
    @submit.like|=1
      if(@submit.title.empty?) 
        respond_to do |format|
        format.html { render :new }
        format.json { render json: {"status": 422,
          "error": "Unprocessable entity",
          "message": "You provided neither title nor url or text or wrong URL"}, status: :unprocessable_entity }
        end
      else 
        if(@submit.URL.empty? || Submit.exists?(:URL=> @submit.URL) == false)
          temp_text=@submit.text
          if(!@submit.URL.empty? && !@submit.text.empty?) 
            @submit.text=""
          end
      
          respond_to do |format|
            if @submit.save
              user = User.find(session[:user_id])
              user.update('karma': user.karma + 1)
              session[:user_karma] += 1
        
              if(!@submit.URL.empty? && !temp_text.empty?)
              @comentari = Comentari.new(:text => temp_text, :user_id =>@submit.user_id, :postID => @submit.id.to_i, :respondsToId => "0", :likes => 1)
              @comentari.save
              end

              format.html { redirect_to "/submit/newest", notice: 'Submit was successfully created.' }
              format.json { render @submit, status: :created}
            else
              format.html { render :new }
              format.json { render json: {"status": 422,
                "error": "Unprocessable entity",
                "message": "Failed to save"}, status: :unprocessable_entity }
            end
          end
        else
          respond_to do |format|
            @s = Submit.all.where(:URL => @submit.URL)
              format.html { redirect_to "/submits/" + @s.pluck(:id).join() , notice: 'URL already exists.' }
              format.json { render json: @s, status: :conflict }
            end
        end
      end
    end
  end
  # POST /submits/comment
  def comment
    params.permit!
    if params[:comentari][:text].blank?
    else
    @comment = Comentari.new(params[:comentari])
    respond_to do |format|
      if @comment.save
        user = User.find(session[:user_id])
        user.update('karma': user.karma + 1)
        session[:user_karma] += 1
        format.html { redirect_to "/submits/"+@comment.postID.to_s, notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end
  end
  # PATCH/PUT /submits/1
  # PATCH/PUT /submits/1.json
  def update
    respond_to do |format|

hacker_news_ASW/app/helpers/submits_helper.rb
module SubmitsHelper
end

hacker_news_ASW/app/views/submits/_form.html.erb
<%= form_with(model: submit) do |form| %>
  <% if submit.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(submit.errors.count, "error") %> prohibited this submit from being saved:</h2>

      <ul>
        <% submit.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :URL %>
    <%= form.text_field :URL %>
  </div>

  <div class="field">
    <%= form.label :text %>
    <%= form.text_field :text %>
  </div>

  <div class="field">
    <%= form.label :creator %>
    <%= form.text_field :creator %>
  </div>

  <div class="field">
    <%= form.label :like %>
    <%= form.number_field :like %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

hacker_news_ASW/app/views/submits/ask.html.erb
<center>
<table id="hnmain" width="85%" cellspacing="0" cellpadding="0" border="0" bgcolor="#f6f6ef">
  <tbody>
    <tr>
      <td bgcolor = "#ff6600"  class="tda">
        <table style="padding:2px" width="100%" cellspacing="0" cellpadding="0" border="0">
          <tbody >
            <tr>
               <td style="width:18px; padding-right:4px"  class="tda">
                 <a href="https://www.youtube.com/watch?v=PwbqAJKNdXo">
                   <img src="/y18.gif" style="border:1px white solid;"
                   width = "18" height = "18" >
                 </a>
                </td>
                <td style = "line-height:12pt; height:10px;"  class="tda">
                  <span class="pagetop">
                    <div style="display: inline-block;">
                      <b class="hnname"><a href=<%=index_submit_path%>>Hacker News</a></b>
                     <a  style="color: black"href=<%=newest_submit_path%>>new</a> | 
                     </div>
                     <% if session[:user_name]%>
                      <a href="/comentaris">threads</a>
                    <% else %>
                      <div style="display: inline-block">
                        <%= button_to "threads", '/auth/google_oauth2', form_class: "submit-button" %>
                      </div>
                    <% end%>
                    <div style="display: inline-block;">
                      | <a style="color: black">past</a> | <a style="color: black">comments</a> | <a style="color: black" href=<%=ask_submit_path%>>ask</a> | <a style="color: black">show</a> | <a style="color: black">jobs</a> |
                     </div>
                    <% if session[:user_name]%>
                      <a href=<%= new_submit_path %>>submit</a>
                    <% else %>
                      <div style="display: inline-block">
                        <%= button_to "submit", '/auth/google_oauth2', form_class: "submit-button" %>
                      </div>
                    <% end%>
                  </span>
                </td>
                <td style="text-align:right;padding-right:4px;"  class="tda">
                  <span class="pagetop">
                    <% if session[:user_name]%>
                  <a href=<%= "/users/" + session[:user_id].to_s %>> <%= session[:user_name] + " ("  + session[:user_karma].to_s + ")"%> </a>
                  <p style="display: inline"> | </p>
                  <a style="display: inline" href=<%= logout_path %>>logout</a>
                    <% else %>
                      <%= button_to "login", '/auth/google_oauth2', form_class: "login-button" %>
                    <% end%>
                  </span>
                </td>
            </tr>
            </tbody>
        </table>
      </td>
    </tr>
    <tr id="pagespace" title="" style="height:10px"></tr>
    <tr>
      <td>
         <table class="itemlist" cellspacing="0" cellpadding="0" border="0">
          <tbody>
    <% @count = 1%>
    <% @submit.each do |submit| %>
      <tr class="athing">
        <td class="num" valign="top" align="right"><span class="rank"><%=@count%>.</span></td>
        <td style="display: flex">
        <div style="margin-right: 5px">
        <% if session[:user_email]%>
          <% if  submit.user_id == session[:user_id] %>
            <center><div style="color: #ff6600">*</div></center>
          <% elsif !@current_user_likes.exists?(submit_id: submit.id) %>
            <center><a rel="nofollow" data-method="put" href=<%= "/submits/" + submit.id.to_s + "/upvote_update"%>><div class="votearrow" title="upvote"></div></a></center>
          <% else %>
            <a rel="nofollow" data-method="put" href=<%= "/submits/" + submit.id.to_s + "/upvote_update"%>><div class="votearrow" style="transform: rotate(180deg);" title="upvote"></div></a>
          <% end %>
        <% end %>
        </div>
        
        <a class="storylink" href = "/submits/<%=submit.id%>"><%= submit.title %></a> 
        
         <%if submit.URL!=""%>
               <a href=<%=submit.URL%> class="link">(<%=  submit.URL %>)</a></td>
                          <%end%>
      </tr>    
      <tr>
         <td colspan="1"></td>
         <td class="subtext">
         <span class="score"><%= submit.like %> likes</span> by <a class="hnuser" href=<%= "/users/" + submit.user_id.to_s %>><%= User.find(submit.user_id).name %> | </a> <span class="age"><a><% time = (Time.now() - submit.created_at) %>

                                <% if time < 3600 %>
                                    <a ><%= (time/60).round %> minutes ago</a>  | 
                                <% end %>

                                <% if time >= 3600 && time < 3600*24 %>
                                    <a ><%= (time/3600).round %> hours ago</a> | 
                                <% end %>

                                <% if time >= 3600*24 %>
                                    <a><%= (time/(3600*24)).round %> days ago</a> | 
                                <% end %> </a> </span> 
         <span></span> <a>hide</a> | <a ><%= Comentari.where(postID: submit.id).count.to_s + " comments" %></a>
          </td>
      </tr>
      </tr>
      <%@count+=1%>
    <% end %>
          </tbody>
        </table>
      </td>
    </tr>
  </tbody>
</table>
</center>
<br>

hacker_news_ASW/app/views/submits/edit.html.erb
<h1>Editing Submit</h1>

<%= render 'form', submit: @submit %>

<%= link_to 'Show', @submit %> |
<%= link_to 'Back', submits_path %>

hacker_news_ASW/app/views/submits/show.html.erb
<center>
<table id="hnmain" width="85%" cellspacing="0" cellpadding="0" border="0" bgcolor="#f6f6ef">
  <tbody>
    <tr>
      <td bgcolor = "#ff6600"  class="tda">
         <table style="padding:2px" width="100%" cellspacing="0" cellpadding="0" border="0">
          <tbody >
            <tr>
               <td style="width:18px; padding-right:4px"  class="tda">
                 <a href="https://www.youtube.com/watch?v=PwbqAJKNdXo">
                   <img src="/y18.gif" style="border:1px white solid;"
                   width = "18" height = "18" >
                 </a>
                </td>
                <td style = "line-height:12pt; height:10px;"  class="tda">
                  <span class="pagetop">
                    <div style="display: inline-block;">
                      <b class="hnname"><a href=<%=index_submit_path%>>Hacker News</a></b>
                     <a  style="color: black"href=<%=newest_submit_path%>>new</a> | 
                     </div>
                     <% if session[:user_name]%>
                      <a href="/comentaris">threads</a>
                    <% else %>
                      <div style="display: inline-block">
                        <%= button_to "threads", '/auth/google_oauth2', form_class: "submit-button" %>
                      </div>
                    <% end%>
                    <div style="display: inline-block;">
                      | <a style="color: black">past</a> | <a style="color: black">comments</a> | <a style="color: black" href=<%=ask_submit_path%>>ask</a> | <a style="color: black">show</a> | <a style="color: black">jobs</a> |
                     </div>
                    <% if session[:user_name]%>
                      <a href=<%= new_submit_path %>>submit</a>
                    <% else %>
                      <div style="display: inline-block">
                        <%= button_to "submit", '/auth/google_oauth2', form_class: "submit-button" %>
                      </div>
                    <% end%>
                  </span>
                </td>
                <td style="text-align:right;padding-right:4px;"  class="tda">
                  <span class="pagetop">
                    <% if session[:user_name]%>
                  <a href=<%= "/users/" + session[:user_id].to_s %>> <%= session[:user_name] + " ("  + session[:user_karma].to_s + ")"%> </a>
                  <p style="display: inline"> | </p>
                  <a style="display: inline" href=<%= logout_path %>>logout</a>
                    <% else %>
                      <%= button_to "login", '/auth/google_oauth2', form_class: "login-button" %>
                    <% end%>
                  </span>
                </td>
            </tr>
            </tbody>
        </table>
      </td>
    </tr>
    <tr id="pagespace" title="<%= @submit.title%>" style="height:10px"></tr>
    <tr>
      <td>
        
        <table class="fatitem" border="0">
          <tbody
            <tr class="athing" id="26671928">
              <td align="right" valign="top" class="title"><span class="rank"></span></td>  
              <td style="display: flex">
              <div style="margin-right: 5px">
              <% if session[:user_email]%>
                <% if !@current_user_likes.exists?(submit_id: @submit.id) %>
                  <center><a rel="nofollow" data-method="put" href=<%= "/submits/" + @submit.id.to_s + "/upvote_update"%>><div class="votearrow" title="upvote"></div></a></center>
                <% else %>
                  <a rel="nofollow" data-method="put" href=<%= "/submits/" + @submit.id.to_s + "/upvote_update"%>>unvote</a>
                <% end %>
              <% end %></div></td>
                <td class="title">
                  <%
                    @link = "/submits/" + @submit.id.to_s
                    if @submit.URL!=""
                      @link = @submit.URL
                    end
                    %>
                  <a href="<%=@link %>" class="storylink"><%=@submit.title%></a>
                  <%if @submit.URL!=""%>
                  <%@uri = URI(@submit.URL)%>
                  <span class="sitebit comhead">
                    (<a href = <%=@submit.URL%>><span class="sitestr"><%=@uri.host%></span></a>)
                  </span>
                  <%end%>
                </td>
              </tr>
              <%if @submit.text != ""%>
                <tr>
                  <td colspan="2"></td>
                  <td><%=@submit.text%></td>
                </tr>
              <%end%>
              <tr>
                <td colspan="2"></td>
                <td class="subtext">
                <span class="score" id="score_26671928">
                  <%=@submit.like%> likes
                </span> by 
                <a class="hnuser" href=<%= "/users/" + session[:user_id].to_s %>><%= User.find(@submit.user_id).name %>
                </a> 
                <span class="age">
                  <a><% time = (Time.now() - @submit.created_at) %>

                                <% if time < 3600 %>
                                    <a ><%= (time/60).round %> minutes ago</a>  | 
                                <% end %>

                                <% if time >= 3600 && time < 3600*24 %>
                                    <a ><%= (time/3600).round %> hours ago</a> | 
                                <% end %>

                                <% if time >= 3600*24 %>
                                    <a><%= (time/(3600*24)).round %> days ago</a> | 
                                <% end %> </a>
                  </span> 
                  <span id="unv_26671928"></span>  <a >hide</a> | <a class="hnpast">past</a> | <a>favorite</a> | <a>0&nbsp;comments</a>              
                </td>
              </tr>
              <tr style="height:10px"></tr>
              <tr><td colspan="2"></td>
              <td>
                <% if session[:user_id]%>
                  <form method="post" action="comment">
                <% end%>
                  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
                  <input type="hidden" name="comentari[user_id]" value=<%= session[:user_id].to_i %>>
                  <input type="hidden" name="comentari[postID]" value="<%= @submit.id%>">
                  <input type="hidden" name="comentari[respondsToId]" value="0">
                  <input type="hidden" name="comentari[likes]" value="1">
                  <textarea name="comentari[text]" rows="6" cols="60"></textarea>
                  <br><br>
                  <span class="subtext">If you haven't already, would you mind reading about HN's 
                    <a href="newswelcome.html"><u>approach to comments</u></a>
                    and <a href="newsguidelines.html"><u>site guidelines</u></a>?
                  </span>
                  <br><br>
                  <% if session[:user_id]%>
                    <input type="submit" value="add comment">
                  <% else %>
                    <%= button_to "add comment", '/auth/google_oauth2' %>
                  <% end%>
                <% if session[:user_id]%>
                  </form>
                <% end%>
              </td>
            </tr>
          </tbody>
        </table>
        </br></br>
        <table>
          <tbody>
            <%
            @comment = @comment.to_a
            arrOffsets = Array.new(@comment.size, 0)
            for i in 0..@comment.length-1
              if @comment[i].respondsToId == 0
              else
                #busquem el comentari que respon
                j = 0
                while @comment[j].id!=@comment[i].respondsToId and j<@comment.length do 
                j=j+1
                end
                if(@comment[j].id==@comment[i].respondsToId) 
                  @comment.insert(j+1, @comment.delete_at(i))
                  arrOffsets.insert(j+1, arrOffsets.delete_at(i))
                  arrOffsets[j+1] = arrOffsets[j]+1
                  i=i-1
                end
              end
            end
            %>
             <% for i in 0..@comment.length-1%>
             <tr class="athing comtr" id="<%=@comment[i].id%>">
               <td>
                <table border="0">  
                  <tbody>
                    <tr>
                      <td class="ind"><img src="s.gif" height="1" width="<%=40*arrOffsets[i]%>"></td>
                      <td style="display: flex">
                      <div style="margin-right: 5px">
                      <% if session[:user_email]%>
                        <% if  @comment[i].user_id == session[:user_id] %>
                          <center><div style="color: #ff6600">*</div></center>
                        <% elsif !@current_user_likes_comment.exists?(comentari_id: @comment[i].id) %>
                          <center><a rel="nofollow" data-method="put" href=<%= "/comentaris/" + @comment[i].id.to_s + "/upvote_comment_update"%>><div class="votearrow" title="upvote"></div></a></center>
                        <% else %>
                          <a rel="nofollow" data-method="put" href=<%= "/comentaris/" + @comment[i].id.to_s + "/upvote_comment_update"%>><div class="votearrow" style="transform: rotate(180deg);" title="upvote"></div></a>
                        <% end %>
                      <% end %></div></td>
                      <td class="default">
                        <div style="margin-top:2px; margin-bottom:-10px;">
                          <span class="comhead">
                            <a class="hnuser" href=<%= "/users/" + session[:user_id].to_s %>><%=User.find(@comment[i].user_id).name%></a> 
                            <span class="age">
                              <a><% time = (Time.now() - @comment[i].created_at) %>

                              <% if time < 3600 %>
                                <a ><%= (time/60).round %> minutes ago</a>   
                              <% end %>

                              <% if time >= 3600 && time < 3600*24 %>
                                  <a ><%= (time/3600).round %> hours ago</a>  
                              <% end %>

                              <% if time >= 3600*24 %>
                                  <a><%= (time/(3600*24)).round %> days ago</a>  
                              <% end %> </a>
                            </span> 
                            <span id="unv_26672023"></span>
                            <span class="par"></span> 
                            <!--<a class="togg" n="3" href="javascript:void(0)" onclick="return toggle(event, 26672023)">[–]</a>-->
                            <span class="storyon"></span>
                          </span>
                        </div>
                        <div class="comment">
                          <span class="commtext c00"><%= simple_format(@comment[i].text)%>
                            <div class="reply">        
                              
                                <font size="1">
                                  <u><a href="/comentaris/<%=@comment[i].id%>">reply</a></u>
                                </font>
                              </br>
                            </div>
                          </span>
                        </div>
                      </td>
                    </tr>
                  </tbody>
                </table>
              </tr>
             <% end %>
          </tbody>
        </table>
        
      </td>
    </tr>
  </tbody>
</table>
</center>


<!--
<p>
  <strong>Title:</strong>
  <%= @submit.title %>
</p>

<p>
  <strong>Url:</strong>
  <%= @submit.URL %>
</p>

<p>
  <strong>Text:</strong>
  <%= @submit.text %>
</p>

<p>
  <strong>user_id:</strong>
  <%= User.find(@submit.user_id).name %>
</p>

<p>
  <strong>Like:</strong>
  <%= @submit.like %>
</p>

<%= link_to 'Edit', edit_submit_path(@submit) %> |
<%= link_to 'Back', submits_path %>
-->